spring.application.name=ms-rutaexpress-bff
server.port=${SERVER_PORT:8080}
rutaexpress.shipments.base-url=${SHIPMENTS_BASE_URL:http://localhost:8081}
rutaexpress.catalog.base-url=${CATALOG_BASE_URL:http://localhost:8082}
rutaexpress.http.connect-timeout=${DOWNSTREAM_CONNECT_TIMEOUT:3s}
rutaexpress.http.read-timeout=${DOWNSTREAM_READ_TIMEOUT:10s}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_ISSUER_URI}
rutaexpress.security.audience=${AZURE_AUDIENCE}
rutaexpress.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}
